# Generated by Django 4.0.6 on 2022-08-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Person',
        ),
    ]
